// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppGuessInput: typeof import('./components/AppGuessInput.vue')['default']
    AppInput: typeof import('./components/AppInput.vue')['default']
    AppProgress: typeof import('./components/AppProgress.vue')['default']
    AppPwaReload: typeof import('./components/AppPwaReload.vue')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiLogout: typeof import('~icons/mdi/logout')['default']
    IconMdiMusicNote: typeof import('~icons/mdi/music-note')['default']
    IconMdiPlayCircle: typeof import('~icons/mdi/play-circle')['default']
    IconMdiSpotify: typeof import('~icons/mdi/spotify')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
